version: "3"
services:
  api:
    image: registry.gitlab.com/niclastimmdev/fast-template:latest
    restart: unless-stopped
    deploy:
      mode: replicated
      replicas: 3
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.api-http.rule=Host(`api.niclastimm.dev`)
        - traefik.http.routers.api-http.entrypoints=http
        - traefik.http.routers.api-https.rule=Host(`api.niclastimm.dev`)
        - traefik.http.routers.api-https.entrypoints=https
        - traefik.http.routers.api-https.tls=true
        - traefik.http.routers.api-https.tls.certresolver=le
        - traefik.http.services.api.loadbalancer.server.port=8000
      resources:
        limits:
          memory: 128M
    depends_on:
      - db
    networks:
      - traefik-public
      - fast-api_fast-template

  # Database
  db:
    volumes:
      - fastapi-template:/var/lib/postgresql/data
    networks:
      - fast-api_fast-template

  # Redis
  redis:
    networks:
      - fast-api_fast-template

# NETWORKS
networks:
  fast-api_fast-template:
    #attachable: true
    driver: overlay
  traefik-public:
    external: true

# VOLUMES
volumes:
  fastapi-template:
    driver: local
