# Controllers
controllers:
  - "app.core.user"

# SSH connection settings
ssh:
  live:
    host: "api.niclastimm.dev"
    user: "root"
    dir: "/var/www/fast-template"

# CLI commands.
commands:
  - app.core.user
  - app.core.db
  - app.core.ssh
